dds_project/dds/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.OperationListView.as_view(), name='operation_list'),
    path('create/', views.OperationCreateView.as_view(), name='operation_create'),
    path('<int:pk>/edit/', views.OperationUpdateView.as_view(), name='operation_edit'),
    path('<int:pk>/delete/', views.OperationDeleteView.as_view(), name='operation_delete'),
    path('load-categories/', views.load_categories, name='load_categories'),
    path('load-subcategories/', views.load_subcategories, name='load_subcategories'),
    path('dictionaries/statuses/', views.StatusListView.as_view(), name='status_list'),
    path('dictionaries/statuses/create/', views.StatusCreateView.as_view(), name='status_create'),
    path('dictionaries/statuses/<int:pk>/edit/', views.StatusUpdateView.as_view(), name='status_edit'),
    path('dictionaries/statuses/<int:pk>/delete/', views.StatusDeleteView.as_view(), name='status_delete'),
    path('dictionaries/types/', views.OperationTypeListView.as_view(), name='type_list'),
    path('dictionaries/types/create/', views.OperationTypeCreateView.as_view(), name='type_create'),
    path('dictionaries/types/<int:pk>/edit/', views.OperationTypeUpdateView.as_view(), name='type_edit'),
    path('dictionaries/types/<int:pk>/delete/', views.OperationTypeDeleteView.as_view(), name='type_delete'),
    path('dictionaries/categories/', views.CategoryListView.as_view(), name='category_list'),
    path('dictionaries/categories/types/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('dictionaries/categories/<int:pk>/edit/', views.CategoryUpdateView.as_view(), name='category_edit'),
    path('dictionaries/categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('dictionaries/subcategories/', views.SubcategoryListView.as_view(), name='subcategory_list'),
    path('dictionaries/subcategories/types/create/', views.SubcategoryCreateView.as_view(), name='subcategory_create'),
    path('dictionaries/subcategories/<int:pk>/edit/', views.SubcategoryUpdateView.as_view(), name='subcategory_edit'),
    path('dictionaries/subcategories/<int:pk>/delete/', views.SubcategoryDeleteView.as_view(), name='subcategory_delete')
]

dds_project/dds_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dds.urls')),
]

dds_project/dds/models.py
import datetime as dt

from django.db import models
from django.core.validators import MinValueValidator
from django.forms import ValidationError
from django.utils import timezone


class Status(models.Model):

    name = models.CharField(max_length=64, verbose_name='Название статуса')

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.name[:20]

    def get_list_fields(self):
        return [self.name]


class OperationType(models.Model):

    name = models.CharField(max_length=64, verbose_name='Тип операции')

    class Meta:
        verbose_name = 'Тип операции'
        verbose_name_plural = 'Типы операций'

    def __str__(self):
        return self.name[:20]

    def get_list_fields(self):
        return [self.name]


class Category(models.Model):

    name = models.CharField(max_length=64, verbose_name='Название категории')
    operation_type = models.ForeignKey(
        OperationType, on_delete=models.CASCADE, verbose_name='Тип операции'
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name[:20]

    def get_list_fields(self):
        return [self.name, self.operation_type]


class Subcategory(models.Model):

    name = models.CharField(
        max_length=64, verbose_name='Название подкатегории'
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Категория'
    )

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def __str__(self):
        return self.name[:20]

    def get_list_fields(self):
        return [self.name, self.category]


class MoneyOperation(models.Model):

    created_at = models.DateField(
        default=timezone.localdate,
        verbose_name='Дата создания записи'
    )
    status = models.ForeignKey(
        Status, on_delete=models.PROTECT, verbose_name='Статус'
    )
    operation_type = models.ForeignKey(
        OperationType, on_delete=models.PROTECT, verbose_name='Тип операции'
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name='Категория'
    )
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.PROTECT, verbose_name='Подкатегория'
    )
    amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0.01)],
        verbose_name='Сумма'
    )
    comment = models.TextField(
        blank=True, null=True, verbose_name='Комментарий'
    )

    class Meta:
        verbose_name = 'Денежная операция'
        verbose_name_plural = 'Денежные операции'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.created_at.date()} - {self.amount} ₽ ({self.status})'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def clean(self):
        if isinstance(self.created_at, dt.datetime):
            self.created_at = self.created_at.date()

        if self.created_at > timezone.localdate():
            raise ValidationError(
                {'created_at': 'Дата не может быть в будущем'}
            )

dds_project/dds/forms.py
from django import forms
from django.forms import DateInput
from django.utils import timezone

from .models import (
    Status, OperationType, Category,
    Subcategory, MoneyOperation
)


class MoneyOperationForm(forms.ModelForm):

    class Meta:
        model = MoneyOperation
        fields = '__all__'
        widgets = {
            'created_at': DateInput(
                attrs={
                    'type': 'date',
                    'class': 'form-control'
                },
                format='%Y-%m-%d'
            ),
            'comment': forms.Textarea(
                attrs={'rows': 3, 'class': 'form-control'}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not self.instance.pk:
            self.initial['created_at'] = timezone.localdate().strftime('%Y-%m-%d')

        if 'category' in self.data and self.data['category']:
            self.fields['subcategory'].queryset = Subcategory.objects.filter(
                category_id=self.data['category']
            )
        elif self.instance.pk:
            self.fields['subcategory'].queryset = self.instance.category.subcategory_set
        else:
            self.fields['subcategory'].queryset = Subcategory.objects.none()

        for field_name, field in self.fields.items():
            if field_name not in self.Meta.widgets:
                field.widget.attrs['class'] = 'form-control'


class StatusForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class OperationTypeForm(forms.ModelForm):

    class Meta:
        model = OperationType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class SubcategoryForm(forms.ModelForm):

    class Meta:
        model = Subcategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

dds_project/dds/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import JsonResponse


from .models import (
    Status, OperationType, Category,
    Subcategory, MoneyOperation
)
from .forms import (
    MoneyOperationForm, StatusForm,
    OperationTypeForm, CategoryForm, SubcategoryForm
)
from .filters import MoneyOperationFilter


class OperationListView(ListView):

    model = MoneyOperation
    template_name = 'dds/index.html'
    context_object_name = 'operations'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = MoneyOperationFilter(
            self.request.GET, queryset=queryset
        )
        return self.filterset.qs.order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context


class OperationCreateView(CreateView):

    model = MoneyOperation
    form_class = MoneyOperationForm
    template_name = 'dds/operation_form.html'
    success_url = reverse_lazy('operation_list')

    def form_valid(self, form):
        messages.success(self.request, 'Операция успешно создана')
        return super().form_valid(form)


class OperationUpdateView(UpdateView):

    model = MoneyOperation
    form_class = MoneyOperationForm
    template_name = 'dds/operation_form.html'
    success_url = reverse_lazy('operation_list')

    def form_valid(self, form):
        return super().form_valid(form)


class OperationDeleteView(DeleteView):

    model = MoneyOperation
    template_name = 'dds/operation_confirm_delete.html'
    success_url = reverse_lazy('operation_list')

    def form_valid(self, form):
        messages.success(self.request, 'Операция успешно удалена')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление операции'
        return context


def load_categories(request):
    type_id = request.GET.get('type_id')
    categories = Category.objects.filter(
        operation_type_id=type_id).order_by('name')
    return JsonResponse(list(categories.values('id', 'name')), safe=False)


def load_subcategories(request):
    category_id = request.GET.get('category_id')
    subcategories = Subcategory.objects.filter(
        category_id=category_id).order_by('name')
    return JsonResponse(list(subcategories.values('id', 'name')), safe=False)


class StatusListView(ListView):

    model = Status
    template_name = 'dds/dictionaries/status_list.html'
    context_object_name = 'statuses'
    paginate_by = 10


class StatusCreateView(CreateView):

    model = Status
    form_class = StatusForm
    template_name = 'dds/dictionaries/status_form.html'
    success_url = reverse_lazy('status_list')

    def form_valid(self, form):
        messages.success(self.request, 'Статус успешно создан')
        return super().form_valid(form)


class StatusUpdateView(UpdateView):

    model = Status
    form_class = StatusForm
    template_name = 'dds/dictionaries/status_form.html'
    success_url = reverse_lazy('status_list')

    def form_valid(self, form):
        messages.success(self.request, 'Статус успешно обновлен')
        return super().form_valid(form)


class StatusDeleteView(DeleteView):

    model = Status
    template_name = 'dds/dictionaries/status_confirm_delete.html'
    success_url = reverse_lazy('status_list')

    def form_valid(self, form):
        messages.success(self.request, 'Статус успешно удален')
        return super().form_valid(form)


class OperationTypeListView(ListView):

    model = OperationType
    template_name = 'dds/dictionaries/type_list.html'
    context_object_name = 'types'
    paginate_by = 10


class OperationTypeCreateView(CreateView):

    model = OperationType
    form_class = OperationTypeForm
    template_name = 'dds/dictionaries/type_form.html'
    success_url = reverse_lazy('type_list')

    def form_valid(self, form):
        messages.success(self.request, 'Тип операции успешно создан')
        return super().form_valid(form)


class OperationTypeUpdateView(UpdateView):

    model = OperationType
    form_class = OperationTypeForm
    template_name = 'dds/dictionaries/type_form.html'
    success_url = reverse_lazy('type_list')

    def form_valid(self, form):
        messages.success(self.request, 'Тип операции успешно обновлен')
        return super().form_valid(form)


class OperationTypeDeleteView(DeleteView):

    model = OperationType
    template_name = 'dds/dictionaries/type_confirm_delete.html'
    success_url = reverse_lazy('type_list')

    def form_valid(self, form):
        messages.success(self.request, 'Тип операции успешно удален')
        return super().form_valid(form)


class CategoryListView(ListView):

    model = Category
    template_name = 'dds/dictionaries/category_list.html'
    context_object_name = 'categories'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        type_id = self.request.GET.get('type_id')
        if type_id:
            queryset = queryset.filter(operation_type_id=type_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['types'] = OperationType.objects.all()
        return context


class CategoryCreateView(CreateView):

    model = Category
    form_class = CategoryForm
    template_name = 'dds/dictionaries/category_form.html'
    success_url = reverse_lazy('category_list')

    def form_valid(self, form):
        messages.success(self.request, 'Категория успешно создана')
        return super().form_valid(form)


class CategoryUpdateView(UpdateView):

    model = Category
    form_class = CategoryForm
    template_name = 'dds/dictionaries/category_form.html'
    success_url = reverse_lazy('category_list')

    def form_valid(self, form):
        messages.success(self.request, 'Категория успешно обновлена')
        return super().form_valid(form)


class CategoryDeleteView(DeleteView):

    model = Category
    template_name = 'dds/dictionaries/category_confirm_delete.html'
    success_url = reverse_lazy('category_list')

    def form_valid(self, form):
        messages.success(self.request, 'Категория успешно удалена')
        return super().form_valid(form)


class SubcategoryListView(ListView):

    model = Subcategory
    template_name = 'dds/dictionaries/subcategory_list.html'
    context_object_name = 'subcategories'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.request.GET.get('category_id')
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class SubcategoryCreateView(CreateView):

    model = Subcategory
    form_class = SubcategoryForm
    template_name = 'dds/dictionaries/subcategory_form.html'
    success_url = reverse_lazy('subcategory_list')

    def form_valid(self, form):
        messages.success(self.request, 'Подкатегория успешно создана')
        return super().form_valid(form)


class SubcategoryUpdateView(UpdateView):

    model = Subcategory
    form_class = SubcategoryForm
    template_name = 'dds/dictionaries/subcategory_form.html'
    success_url = reverse_lazy('subcategory_list')

    def form_valid(self, form):
        messages.success(self.request, 'Подкатегория успешно обновлена')
        return super().form_valid(form)


class SubcategoryDeleteView(DeleteView):

    model = Subcategory
    template_name = 'dds/dictionaries/subcategory_confirm_delete.html'
    success_url = reverse_lazy('subcategory_list')

    def form_valid(self, form):
        messages.success(self.request, 'Подкатегория успешно удалена')
        return super().form_valid(form)

dds_project/dds/templates/dds/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Список операций</h5>
        <a href="{% url 'operation_create' %}" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Добавить операцию
        </a>
    </div>
    <div class="card-body">
        <form method="get" class="mb-4">
            <div class="row g-3">
                <div class="col-md-2">
                    {{ filter.form.status|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ filter.form.operation_type|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ filter.form.category|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ filter.form.subcategory|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    <label class="form-label">Период дат</label>
                    <div class="input-group">
                        {{ filter.form.created_at }}
                    </div>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary me-2">Фильтровать</button>
                    <a href="{% url 'operation_list' %}" class="btn btn-outline-secondary">Сбросить</a>
                </div>
            </div>
        </form>

        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Дата</th>
                        <th>Статус</th>
                        <th>Тип</th>
                        <th>Категория</th>
                        <th>Подкатегория</th>
                        <th>Сумма</th>
                        <th>Комментарий</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for operation in operations %}
                    <tr>
                        <td>{{ operation.created_at|date:"d.m.Y" }}</td>
                        <td>{{ operation.status }}</td>
                        <td>{{ operation.operation_type }}</td>
                        <td>{{ operation.category }}</td>
                        <td>{{ operation.subcategory }}</td>
                        <td>{{ operation.amount }} р.</td>
                        <td>{{ operation.comment|default:""|truncatechars:20 }}</td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{% url 'operation_edit' operation.pk %}" class="btn btn-outline-primary">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'operation_delete' operation.pk %}" class="btn btn-outline-danger">
                                    <i class="bi bi-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="8" class="text-center">Нет операций</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                </li>
                {% endif %}
                
                {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock %}

dds_project/dds/templates/dds/operation_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow-sm">
        <div class="card-header bg-danger text-white">
            <h5 class="mb-0">
                <i class="bi bi-exclamation-triangle me-2"></i>Подтверждение удаления
            </h5>
        </div>
        <div class="card-body">
            <p class="lead">Вы уверены, что хотите удалить эту операцию?</p>
            
            <div class="card mb-3">
                <div class="card-body">
                    <h6>Детали операции:</h6>
                    <p><strong>Дата:</strong> {{ object.created_at|date:"d.m.Y" }}</p>
                    <p><strong>Тип:</strong> {{ object.operation_type }}</p>
                    <p><strong>Сумма:</strong> {{ object.amount }} ₽</p>
                    {% if object.comment %}
                    <p><strong>Комментарий:</strong> {{ object.comment }}</p>
                    {% endif %}
                </div>
            </div>

            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    <i class="bi bi-trash me-2"></i>Да, удалить
                </button>
                <a href="{% url 'operation_list' %}" class="btn btn-secondary">
                    <i class="bi bi-x-circle me-2"></i>Отмена
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dds_project/dds/templates/dds/operation_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card shadow-sm">
    <div class="card-header bg-primary text-white">
        <h5 class="mb-0">
            <i class="bi bi-{% if object %}pencil-square{% else %}plus-circle{% endif %} me-2"></i>
            {% if object %}Редактирование операции{% else %}Создание операции{% endif %}
        </h5>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col-md-6">
                    {{ form.created_at|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.status|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.operation_type|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.amount|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.subcategory|as_crispy_field }}
                </div>
                <div class="col-12">
                    {{ form.comment|as_crispy_field }}
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-check-circle me-2"></i>
                        {% if object %}Сохранить{% else %}Создать{% endif %}
                    </button>
                    <a href="{% url 'operation_list' %}" class="btn btn-outline-secondary">
                        <i class="bi bi-x-circle me-2"></i>Отмена
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {

    $("#id_operation_type").change(function() {
        const typeId = $(this).val();
        if (typeId) {
            $.ajax({
                url: "{% url 'load_categories' %}",
                data: { 'type_id': typeId },
                success: function(data) {
                    $("#id_category").html('<option value="">---------</option>');
                    $.each(data, function(i, item) {
                        $("#id_category").append(`<option value="${item.id}">${item.name}</option>`);
                    });
                    $("#id_subcategory").html('<option value="">---------</option>');
                }
            });
        }
    });

    $("#id_category").change(function() {
        const categoryId = $(this).val();
        if (categoryId) {
            $.ajax({
                url: "{% url 'load_subcategories' %}",
                data: { 'category_id': categoryId },
                success: function(data) {
                    $("#id_subcategory").html('<option value="">---------</option>');
                    $.each(data, function(i, item) {
                        $("#id_subcategory").append(`<option value="${item.id}">${item.name}</option>`);
                    });
                }
            });
        }
    });
});
</script>
{% endblock %}